server.port: 8030

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

audit:
  color: "any" # available options: red, blue, green, any